muleHost: 'http://do-qas-esb-01.do.viaa.be:10005'
endpoints:
  stats: '/api/report/global'
  report:
    mam:
      last-day: '/api/report/mam?gran=last-day'
      last-week: '/api/report/mam?gran=last-week'
      last-month: '/api/report/mam?gran=last-month'
      last-year: '/api/report/mam?gran=last-year'
    ams:
      last-day: '/api/report/ams?gran=last-day'
      last-week: '/api/report/ams?gran=last-week'
      last-month: '/api/report/ams?gran=last-month'
      last-year: '/api/report/ams?gran=last-year'

# used to map SAML data to available services
services:
  map:
    mediahaven: 'MAM'
    amsweb: 'AMS'
    FTP: 'FTP'
    skryvweb: 'DBS'
  always:
    FTP: true

# general app settings
app: # used in console to tell which app is started
  name: 'mijn.VIAA'
  port: 80
  sessionSecret: 'mijnVIAAetc'

# toggle to show api links on /api/docs
showApiDocs: false
# replace all outgoing calls to Mule by dummy data
dummyRequest: false
# fake that these services are available when not logged in
fakeServicesAvailable: null
# api delay for testing graph loading
apiDelay:
  min: 0
  max: 0
# show extended error messages in api call responses
showErrors: false
# log errors in server console
logErrors: false
authenticationEnabled: false
# settings for authentication
passport:
  strategy: 'saml'
  saml:
    # URL that goes from the Identity Provider -> Service Provider
      callbackUrl: 'mijn-qas.viaa.be/login/callback'

      # URL that goes from the Service Provider -> Identity Provider
      entryPoint: 'https://idp-qas.viaa.be/saml2/idp/SSOService.php'

      # Url to logout from the Identity Provider
      logoutUrl: 'https://idp-qas.viaa.be/saml2/idp/SingleLogoutService.php'

      issuer: 'mijn-tst.viaa.be'

      identifierFormat: null

      # Service Provider private key
      #decryptionPvk: ''
      
      # Service Provider Certificate
      #privateCert: ''
      
      # Identity Provider's public key
      cert: ''

      validateInResponseTo: false
      disableRequestedAuthnContext: true
