muleHost: 'http://do-qas-esb-01.do.viaa.be:10005'
endpoints:
  stats: '/api/report/global'
  report:
    mam:
      last-day: '/api/report/mam?gran=last-day'
      last-week: '/api/report/mam?gran=last-week'
      last-month: '/api/report/mam?gran=last-month'
      last-year: '/api/report/mam?gran=last-year'
    ams:
      last-day: '/api/report/ams?gran=last-day'
      last-week: '/api/report/ams?gran=last-week'
      last-month: '/api/report/ams?gran=last-month'
      last-year: '/api/report/ams?gran=last-year'

# used to map SAML data to available services
services:
  map:
    mediahaven: 'MAM'
    amsweb: 'AMS'
    FTP: 'FTP'
    skryvweb: 'DBS'
  always:
    FTP: true

# general app settings
app: # used in console to tell which app is started
  name: 'mijn.VIAA'
  port: 80
  sessionSecret: 'mijnVIAAetc'

# toggle to show api links on /api/docs
showApiDocs: false
# replace all outgoing calls to Mule by dummy data
dummyRequest: false
# fake that these services are available when not logged in
fakeServicesAvailable: null
# api delay for testing graph loading
apiDelay:
  min: 0
  max: 0
# show extended error messages in api call responses
showErrors: false
# log errors in server console
logErrors: false
authenticationEnabled: false
# settings for authentication
passport:
  strategy: 'saml'
  saml:
    # URL that goes from the Identity Provider -> Service Provider
      callbackUrl: 'mijn-qas.viaa.be/login/callback'

      # URL that goes from the Service Provider -> Identity Provider
      entryPoint: 'https://idp-qas.viaa.be/saml2/idp/SSOService.php'

      # Url to logout from the Identity Provider
      logoutUrl: 'https://idp-qas.viaa.be/saml2/idp/SingleLogoutService.php'

      issuer: 'mijn-tst.viaa.be'

      identifierFormat: null

      # Service Provider private key
      #decryptionPvk: '-----BEGIN RSA PRIVATE KEY-----MIIJKAIBAAKCAgEAydJm2g7F+9EEphLqPB7l3BL/uAXm07NB1vonMpNJ8YeXZOc3X9OIJ5PJYZFEDEY/zFRaVV6B5MevRIzLYAC9Sudzt4JtA1ZbtN32zbhebvLCjuzLmGe2hh3nFsTcuJ06zYKkMNUOHK0qp/dESZFk+/sHJVZzbEPmtNtTkFJctzHzN9q9A5pr3JXpc0Lh4uiv3UWjHpQQ2j3tl4/zAl6uQIwa1Xq4S3KHXKrNlX7MJoLS66liC9RxUeOyl291pDA1cmGtGBuTSKCNNywzutPQne/UUNVJlysqJCHIT2eH9xIiub9DDJQyIIAwn91ZAymGrbEC+aTAnygnvHQ6Ye5nDo2OxSeLj0V5pJmKo4IOu1xmxBAEp0/378Asb+7HDE8I/ODePSluh2cJ5sqHz2noa1m3d1jf7zEhqrjXf8iF2m9nTWm7nnSk3yNhqOgzFydd0h66osHrMl7Xo1UnxiKbyzhrDKq/W6YB0uC2TdCUbMXfpOeRFl/XckkxYt7b2GXvBwtlPpb3r/nPnnUL0EiFXnWcBGHunpCw0izNqQH7DN1E/Esa6S1szZwgDEOq6Z4B+Jc8n72YBnja/Csc0f7EoUdVdaX5GXXMWKfIYF6/UjTdV6VmtHcjJYYdcsSDEteVxnpRRdSNGJbwL5kuBMM0BYlCGhAa2hpJVPg0GL/A1BECAwEAAQKCAgANqFpjeUp2nw90eaU2SlT9zp9Vgbi8LM5Q0P7kEkmXubhKEMeTiYoWO48ONjlnpz1cA31Vd57Mr6KxveFpbsNglUckbQQZjLeKBtdT1p01XuJBr86bUrFsZAumY84YBDPdgnDACTr6P9G6KiaJ3/f4gWVbZn1LH1E2ff0qsBgsIYo3BmtyGfogpFh2/1iv9VUpYTQHtrdpPXWdoxUr3OJn5dNPDQ35tRdp8vkUm88O8B176yuCZ27/vqvwSY+pe8WyJuAC2KLf8FV+HVSm2PyuI3O3wKdJPpeMeGjIztXJp4WIEmRkLocx4drohp8mcqH1kRwFbtvGKX5+51KoG+0HVUURHmy2QUUEJ2FHb79yYehYITVsNYXlcNfVpXH9AGgwbATJvlmMjTU+0QPnYy6FP7kcGxUtoA/mfbZzsfRinuXdl1e/W6hxNR2xvK0UDDKYzD8g2fkCl5C/ZAaRaU1R24jps4nPcK6dWI+5NtNwA65Klj1ti8FXdH9T3DPl1gzPC8PXOnYUrjktftAlqs9c4WeK79c8Q5Pw1vLufmuxgerFA5i9Sc8Es1BB9J1HFj1I7sgDFBBVcBRPQ7u0m9ffZ8rvMHEjb76KorMJ7c3UK1NA1L9lmH8xv63FFkLjXtrOfH057d3qyf7hwKh9H9b1Ux+T6banuwPVS4EJ0OSCUQKCAQEA8WuAvs7SvVcgFbrdqB6ZyHV/aRhLA5aLpC7ANxLQLZTOrqo8eEMbPa9YEginWaonsH85dvBmgw4oyp5lOiX+8yhu0fXcACB/aXcUR9KnXy5x3XysFYdVpYJVeaO6NeNElwy8MCKP+U3ArhRZamY8tHWGgiSt6TBdRzPSfZVHjazui38o8tpDUGqK10HEohzcxKonzjr0Gi2D0cyxr9r6LLg1xhQxITESFDe/jMC1MNB8zqPmtvsDptXNnLMYyKiAy4c/lQva1ruzTiHuU420Wu723ulM/rz+adMX/W91ju+JtzmXfouaYNnglBPFkJWo/OiuGY9KV1VbOomzVtfyHQKCAQEA1gKwcAUjoCG+KC5Gg3noWrKFgBoNgpNwTcorZq65tl4GWwA9PDTlC/wQaJEkiZThk37J6Bh545zMPfD8DhwsVqPbHhLWLEKFJ/D/C7GcU/O/rfAl07ULnofBmsDcbStTujPRHeFfEeNYJcGoSflheMc1vkH+iCYs20VodogUKrTmiVBo+aRfMdwAZS8XFOM+K0rZqy9cB1PGtq45Vc8I13BhQMErdiL/c4ijP4frm8EHpErOJeAOSIoY6GeCobwep+LRuPBA0lLygvDQUFwLV6Bxg86Zoy8DcfqJpYqLWM0uMur6wWD8dK1w7f/hUlx9j5Zf8J/pe0ljH3x89vJHhQKCAQBf9u63ajlFAFQFr0Ea6gcRMvuRiBGRfI9HlTnc6oKMC+HYdl0RJQO4EnI8wOnc75FVTE1IZSkqoT8/w5TTd3UPrRvYJBXuivx6rNYH8smLQUgL1doFuMUnxFY7wwRrFUsXi/1mWObIH8sep4IflEI/LZRpOTFUR2BcxFHAj81gmMQ9+S8K0g398kv8Yu1Jz5VGK6klBjQwD7WdePOMxsu5aQQfF7mryvi3xq1CwvuDSuzBq08znzYFZGmWB28rnCeOP9XbZln4D6anwT8eQW7W0rSZST3M6M1svXeEy4B8b+VbSu5YZB/areDim7Vl0sfYuJk0GcxgSNK5wzDhrXdVAoIBAQC799y0Zy8lRL3aWNrCO97jWo17OGbJW2p2SK3aIHkpPmhioVEngmXzIs/eqCzpUoTWobQBUQ4t5thVR0Z7ti8TYhPg1Dac5UhDDp9UzAk8i4i944G18vxjn2Vi4SY6FKYTk9OGZR61fXM8pl2Dq6/6/y2rEBfZyX34kXvxMBBWelFKJgAt1DtwdYU7WiLxy64dJD8O5if0n5aXeWsOfSuM3j3tPD1KI+8usMKB2IYOZXqqyLFL/wFMoU7DQbcxCyP53XTK9OpaUVSDwbOWAWJM8rUBSgMTmwVxpNYlOgyuUHjVbCIWm3LhoDziLa7gQjBeX3ugwzO1f326eALie2ZpAoIBACyJsphpgBSnn6j/ROVLyxC2aB671Czu7SMHeLvsAH0xaVE1uZQKJhjuUfhNxNV2Hp92NX8jTnLcn+cl6t+DpsnIMhDRdZGQprQLH5rgNWwuDdhgXnPx+KQDU3WrcVB/pzFmlcMx7G0YaAv5KljTBfJRDXqAypWM4lixpSAjeyHM/yQDh5Goj2WvFV1sRDHql4JozZQb/sZhIwdrGTVpN90DlXvj4yjxZMDfIKybgXldR0e2SC/tps6Pj/RKqWpIzqp1RtIb9A8KN7zcCbT0IFqKWNa8aodo0OjMhdEv6r/eh3eDATypT4P75wbK9JYoERH3KQEy4vB337KVZdJkJP4=-----END RSA PRIVATE KEY-----'

      # Service Provider Certificate
      #privateCert: '-----BEGIN CERTIFICATE-----MIIFuDCCA6CgAwIBAgIJAP4sPjQy6Wf5MA0GCSqGSIb3DQEBBQUAMEYxCzAJBgNVBAYTAkJFMRgwFgYDVQQIEw9Pb3N0LVZsYWFuZGVyZW4xDjAMBgNVBAcTBUdoZW50MQ0wCwYDVQQKEwRWSUFBMB4XDTE2MDcxMzE1MjEwM1oXDTE4MTIzMDE1MjEwM1owRjELMAkGA1UEBhMCQkUxGDAWBgNVBAgTD09vc3QtVmxhYW5kZXJlbjEOMAwGA1UEBxMFR2hlbnQxDTALBgNVBAoTBFZJQUEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDJ0mbaDsX70QSmEuo8HuXcEv+4BebTs0HW+icyk0nxh5dk5zdf04gnk8lhkUQMRj/MVFpVXoHkx69EjMtgAL1K53O3gm0DVlu03fbNuF5u8sKO7MuYZ7aGHecWxNy4nTrNgqQw1Q4crSqn90RJkWT7+wclVnNsQ+a021OQUly3MfM32r0DmmvclelzQuHi6K/dRaMelBDaPe2Xj/MCXq5AjBrVerhLcodcqs2VfswmgtLrqWIL1HFR47KXb3WkMDVyYa0YG5NIoI03LDO609Cd79RQ1UmXKyokIchPZ4f3EiK5v0MMlDIggDCf3VkDKYatsQL5pMCfKCe8dDph7mcOjY7FJ4uPRXmkmYqjgg67XGbEEASnT/fvwCxv7scMTwj84N49KW6HZwnmyofPaehrWbd3WN/vMSGquNd/yIXab2dNabuedKTfI2Go6DMXJ13SHrqiwesyXtejVSfGIpvLOGsMqr9bpgHS4LZN0JRsxd+k55EWX9dySTFi3tvYZe8HC2U+lvev+c+edQvQSIVedZwEYe6ekLDSLM2pAfsM3UT8SxrpLWzNnCAMQ6rpngH4lzyfvZgGeNr8KxzR/sShR1V1pfkZdcxYp8hgXr9SNN1XpWa0dyMlhh1yxIMS15XGelFF1I0YlvAvmS4EwzQFiUIaEBraGklU+DQYv8DUEQIDAQABo4GoMIGlMB0GA1UdDgQWBBTJxSNfmGBVkwGnvvaDG5fx/wRnETB2BgNVHSMEbzBtgBTJxSNfmGBVkwGnvvaDG5fx/wRnEaFKpEgwRjELMAkGA1UEBhMCQkUxGDAWBgNVBAgTD09vc3QtVmxhYW5kZXJlbjEOMAwGA1UEBxMFR2hlbnQxDTALBgNVBAoTBFZJQUGCCQD+LD40Muln+TAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4ICAQCU0uReIKob0TUXwzhpvfwwspAGlVkpoXBHDugL2Nscik7IygUPU2qMEsoWULD5Z4ET5E7PU9TkDifY9meEU27exg+zN86Thh8KvvckesYkU9RMqB1fODsxeVRahV6HqXQIcUcvkPspifpMwN/JFL4Nk8n8CqEyTSz4V2jUJOAPCPnX6iiSnikbATADEO8tfzPPBdL1gQFz4wDA+j2XGeHss9VrUvIKpWe6nJzg8cjb26qJzeH/3j5+78RflCi0sg0BdCXfU0MPyze+QVXXrqC1oe2QjZLdqX5ZQzIFZFqS4SZQ+0OS9piH1EbhP6MNY1BeJO3/f9cZ8L/fr/f++seMMEXosppox2cI5S3ZOJ34W8htO/03cOTrH0dUO45W1KoElqcY3iF55mqiNVeFEndWnvDcxBs3XJGFrJl+yAGSheZL+2QqmOcHuSFjdF9iFwC3sj8zi5UGatdJDB/FD3yxapLbVX8sQ4ZUrMJrgiPDJS7NOCz3zXkEN233ji0PwtjpUPr3vrYO9sapda8c55KX3nZyzRnBcyITArrLSOsnTx1f23ckeuvZ3XLlK8+GL8bOlP9Htcmqy2XGLmuQ3GFKrCWoq/KtV12evzmm8blZgjg32KWsmzdoDaPu7keCbNKVYvadrveh8EBxmhCRMrx2F4LbIfH2K5LzbrHOgVQc3A==-----END CERTIFICATE-----'

      # Identity Provider's public key
      cert: MIICRjCCAa+gAwIBAgIJALRK8eVTg5r0MA0GCSqGSIb3DQEBBQUAMDwxEDAOBgNVBAMMB3NzbyBpZHAxDDAKBgNVBAsMA3FhczENMAsGA1UECgwEdmlhYTELMAkGA1UEBhMCYmUwHhcNMTUxMjIxMTEyNjAwWhcNMjAxMTI0MTEyNjAwWjA8MRAwDgYDVQQDDAdzc28gaWRwMQwwCgYDVQQLDANxYXMxDTALBgNVBAoMBHZpYWExCzAJBgNVBAYTAmJlMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNP1eVJIdVWXzHeDymWAz5O45YncphIl+V8daO/ltDB8v1OLwET3365Z5CUUO1VRmD+hScISxb5EiHLEHXZywiZJhMIh8J5+bUNfFExpdlKOjhzFp+xtJorqujNyHb/T3fIcmDyJZS/+yU6Lb0nwopv0Y8L2rneU3P/COZM6r5KwIDAQABo1AwTjAdBgNVHQ4EFgQU5zR2gHxHCci97tfB6t3B+C2uWVswHwYDVR0jBBgwFoAU5zR2gHxHCci97tfB6t3B+C2uWVswDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQBVXBWykbbcCUDuFS5PTVZCwYk1M0AUn6d3h/R7kdzUGJMAQ/Rj5iQ9ce30hjOVLZIN1kvwElXnlW27JzM3EOjuZOrwnw73SCHn69vd7cJM5eL+A51TfsF7Pi9IEfHSZsIYJM/Dz4yZTDsNt1t28B/4JaYp6GVS7rFLE+LshGsr/g==

      validateInResponseTo: false
      disableRequestedAuthnContext: true